# Generated by Django 4.2.7 on 2024-01-16 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='valid',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='transfer',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
