# Generated by Django 4.2.7 on 2024-01-16 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0003_auto_20240116_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
