# Generated by Django 4.2.7 on 2024-01-16 17:55

from django.db import migrations, models
import sls.models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0004_auto_20240116_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(default=sls.models.User.create_new_account_number, max_length=4, unique=True),
        ),
    ]
