# Generated by Django 4.2.7 on 2024-01-16 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0006_alter_transfer_userfrom_alter_transfer_userto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='valid',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
