# Generated by Django 4.2.7 on 2024-01-16 19:36

from django.db import migrations
import encrypted_model_fields.fields
import sls.models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0007_alter_transfer_amount_alter_transfer_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedCharField(default=sls.models.User.create_new_account_number),
        ),
        migrations.DeleteModel(
            name='SecureData',
        ),
    ]
