# Generated by Django 4.2.7 on 2024-01-16 19:57

from django.db import migrations
import encrypted_model_fields.fields
import sls.models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0008_user_card_number_delete_securedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=encrypted_model_fields.fields.EncryptedCharField(default=sls.models.User.create_new_personal_id),
        ),
    ]
