# Generated by Django 4.2.7 on 2024-01-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0009_user_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='userToName',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
