# Generated by Django 4.2.7 on 2024-01-16 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sls.models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0010_transfer_usertoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='userTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userTo', to=settings.AUTH_USER_MODEL, to_field='account_number', validators=[sls.models.Transfer.DoesUserExistValidator]),
        ),
    ]
